In [6]:
from Splendor import Splendor
nplayers = 1
GameType = 0
Game = Splendor(nplayers, GameType)

We'll start with a simplified version of Splendor that I used to test my machine learning on.  The most important part of this implementation is the Splendor class.  Calling its constructor starts a new game.  It takes two arguements:  the number of players and the GameType.

In [7]:
print(Game)

Gems: [4 4 4 4 4 5] ; Cards: VPs 15, Bonus 0, cost [1 1 1 0 0]; VPs 3, Bonus 1, cost [1 1 0 1 0]; VPs 1, Bonus 3, cost [0 1 1 1 0]; VPs 2, Bonus 2, cost [1 0 1 0 1];  ; Nobles: VPs 3, Bonus 0, cost [0 0 3 3 3]; VPs 3, Bonus 0, cost [0 3 3 3 0];  ; Players: [VPs 0, gems [0 0 0 0 0 0], cards [0 0 0 0 0], reserved []]


Printing the Splendor object displays the game state:  The gems available, cards available, nobles available, and all Player states.  The gems are displayed as lists of 5 or 6 elements corresponding to the 5 normal gem colors, plus the wild color.  VPs is the number of victory points.  Bonus is the index of the gem type the card will give a discount for (starting from 0).

In [10]:
Game = Splendor(1,0)
print(Game)

Gems: [4 4 4 4 4 5] ; Cards: VPs 2, Bonus 2, cost [1 0 1 0 1]; VPs 15, Bonus 0, cost [1 1 1 0 0]; VPs 3, Bonus 1, cost [1 1 0 1 0]; VPs 1, Bonus 3, cost [0 1 1 1 0];  ; Nobles: VPs 3, Bonus 0, cost [0 4 4 0 0]; VPs 3, Bonus 0, cost [0 3 3 3 0];  ; Players: [VPs 0, gems [0 0 0 0 0 0], cards [0 0 0 0 0], reserved []]


GameType 0 is the simplest implementation I could think of:  Only 4 cards, one of which gives 15 points (the amount needed to win).  All the solver needs to do is pick up the gems [1 1 1 0 0], then buy the only legal card with those gems.

In [11]:
Game = Splendor(1,1)
print(Game)

Gems: [4 4 4 4 4 5] ; Cards: VPs 2, Bonus 2, cost [1 0 0 1 1]; VPs 15, Bonus 0, cost [1 1 0 0 1]; VPs 1, Bonus 3, cost [1 0 1 0 1]; VPs 3, Bonus 1, cost [0 0 0 0 2];  ; Nobles: VPs 3, Bonus 0, cost [0 0 4 4 0]; VPs 3, Bonus 0, cost [0 4 4 0 0];  ; Players: [VPs 0, gems [0 0 0 0 0 0], cards [0 0 0 0 0], reserved []]


GameType 1 is slightly harder.  There is still a card worth 15 points, but its cost is randomized (but always acheivable in one turn).  Now the solver must read the cost of the 15 point card, take those gems, then buy the card.

In [29]:
from Splendor_Full import Splendor_Full
Game = Splendor_Full(1)
print(Game)

Gems: [4 4 4 4 4 5] ; Cards: VPs 0, Bonus 1, cost [1 0 0 0 2]; VPs 0, Bonus 3, cost [0 2 1 0 0]; VPs 0, Bonus 1, cost [1 0 1 1 1]; VPs 0, Bonus 0, cost [3 1 0 0 1]; VPs 3, Bonus 0, cost [6 0 0 0 0]; VPs 1, Bonus 2, cost [3 0 2 3 0]; VPs 2, Bonus 0, cost [0 0 0 5 3]; VPs 2, Bonus 2, cost [4 2 0 0 1]; VPs 4, Bonus 1, cost [6 3 0 0 3]; VPs 4, Bonus 0, cost [3 0 0 3 6]; VPs 3, Bonus 0, cost [0 3 3 5 3]; VPs 4, Bonus 3, cost [0 0 0 7 0];  ; Nobles: VPs 3, Bonus 0, cost [3 3 0 0 3]; VPs 3, Bonus 0, cost [3 0 0 3 3];  ; Players: [VPs 0, gems [0 0 0 0 0 0], cards [0 0 0 0 0], reserved []]


Splendor_Full is the full version of Splendor.  Some of the below syntax will be slightly different because there are 3 decks instead of 1, so a deck # needs to be passed to card buy/reserve methods

# Splendor Class Variables

Below is a list of all relevant class variables.  In a normal game, these should not be changed directly--only read to access the game state.  There are special methods that you should use to take game actions (explained in next section).

The number of unclaimed gems of each type is stored in Game.gems

In [19]:
print(Game.gems)

[4 4 4 4 4 5]


The card data for cards in play (not cards still in the deck) is stored in SplendorCard objects.  The data from those objects can be accessed as below

In [18]:
print(len(Game.cards))
print(type(Game.cards[0]))
print(Game.cards[0])
print(Game.cards[0].VPs)
print(Game.cards[0].bonus)
print(Game.cards[0].cost)

4
<class 'SplendorCard.SplendorCard'>
VPs 2, Bonus 2, cost [1 0 0 1 1]
2
2
[1 0 0 1 1]


The noble data is also stored in SplendorCard objects (because I'm lazy).  Bonuses will not be taken into account and all VPs are 3.

In [21]:
print(len(Game.nobles))
print(type(Game.nobles[0]))
print(Game.nobles[0])
print(Game.nobles[0].VPs)
print(Game.nobles[0].bonus)
print(Game.nobles[0].cost)

2
<class 'SplendorCard.SplendorCard'>
VPs 3, Bonus 0, cost [0 0 4 4 0]
3
0
[0 0 4 4 0]


The player data is stored in a Player object.

In [24]:
print(len(Game.player))
print(type(Game.player[0]))
print(Game.player[0])
print(Game.player[0].gems)
print(Game.player[0].bonuses)
print(Game.player[0].VPs)
print(Game.player[0].reserved)

1
<class 'Player.Player'>
VPs 0, gems [0 0 0 0 0 0], cards [0 0 0 0 0], reserved []
[0 0 0 0 0 0]
[0 0 0 0 0]
0
[]


The game also has a winner varible which is empty until a player has 15 points when CheckWin is called.

In [26]:
Game.CheckWin()
print(Game.winner)
Game.player[0].VPs = 15
Game.CheckWin()
print(Game.winner)

[]
[0]


# Splendor Class Methods

The class methods for preforming game actions come in pairs:  A "Check..." function checks whether the move is legal and returns 1 if it is and 0 if not, and the actual action function preforms the action (if the action is legal).  In the simplified Splendor class, the function generally take the arguements: playern-index of player doing the action, cardn-index of the card involved, gems-length 6 numpy vector describing the number of each gem involved (note that the number of a gem can be negative to represent giving gems back--only useful if you're at the 15 gem limit).

In the Splendor_Full class, the additional arguement "deckn" my be required to indicate the index of the deck the card involved comes from.

In [1]:
from Splendor import Splendor
import numpy as np
np.random.seed(236)
Game = Splendor(1,0)
print(Game)

Gems: [4 4 4 4 4 5] ; Cards: VPs 1, Bonus 3, cost [0 1 1 1 0]; VPs 15, Bonus 0, cost [1 1 1 0 0]; VPs 2, Bonus 2, cost [1 0 1 0 1]; VPs 3, Bonus 1, cost [1 1 0 1 0];  ; Nobles: VPs 3, Bonus 0, cost [4 0 0 0 4]; VPs 3, Bonus 0, cost [3 0 0 3 3];  ; Players: [VPs 0, gems [0 0 0 0 0 0], cards [0 0 0 0 0], reserved []]


In [76]:
#Check gems and TakeGems functions.
playern = 0
gems = np.array([1,2,0,0,0,0])  # Illedal move
print('Validity = %s' % bool(Game.CheckGems(playern,gems)))
gems = np.array([1,1,1,0,0,0])
print('Validity = %s' % bool(Game.CheckGems(playern,gems)))
Game.TakeGems(playern,gems)
print(Game)

Validity = False
Validity = True
Gems: [3 3 3 4 4 5] ; Cards: VPs 1, Bonus 3, cost [0 1 1 1 0]; VPs 15, Bonus 0, cost [1 1 1 0 0]; VPs 2, Bonus 2, cost [1 0 1 0 1]; VPs 3, Bonus 1, cost [1 1 0 1 0];  ; Nobles: VPs 3, Bonus 0, cost [4 0 0 0 4]; VPs 3, Bonus 0, cost [3 0 0 3 3];  ; Players: [VPs 0, gems [1 1 1 0 0 0], cards [0 0 0 0 0], reserved []]


In [77]:
#CheckBuy and BuyCard
gems = np.array([1,1,1,0,0,0])
cardn = 1
playern = 0
print(Game.CheckBuy(playern,cardn,gems))
Game.BuyCard(playern,cardn,gems)
print(Game)

1
Gems: [4 4 4 4 4 5] ; Cards: VPs 1, Bonus 3, cost [0 1 1 1 0]; VPs 2, Bonus 2, cost [1 0 1 0 1]; VPs 3, Bonus 1, cost [1 1 0 1 0];  ; Nobles: VPs 3, Bonus 0, cost [4 0 0 0 4]; VPs 3, Bonus 0, cost [3 0 0 3 3];  ; Players: [VPs 15, gems [0 0 0 0 0 0], cards [1 0 0 0 0], reserved []]


In [2]:
#CheckReserve and ReserveCard
playern = 0
cardn = 0
gems = np.array([0,0,0,0,0,1])
print(Game.CheckReserve(playern,cardn,gems))
Game.ReserveCard(playern,cardn,gems)
print(Game)

1
Gems: [4 4 4 4 4 4] ; Cards: VPs 15, Bonus 0, cost [1 1 1 0 0]; VPs 2, Bonus 2, cost [1 0 1 0 1]; VPs 3, Bonus 1, cost [1 1 0 1 0];  ; Nobles: VPs 3, Bonus 0, cost [4 0 0 0 4]; VPs 3, Bonus 0, cost [3 0 0 3 3];  ; Players: [VPs 0, gems [0 0 0 0 0 1], cards [0 0 0 0 0], reserved [VPs 1, Bonus 3, cost [0 1 1 1 0]]]


# Convenient Solver Stuff

The above is all you'll need to know to work with the game itself.
Additionally, there are some convenient functions for writing solvers in the "Convenient Solver Stuff" folder, which I'll breifly describe here.

MakeMove(Game,playern,Player,NN,Levels) takes your Splendor object, player index, player object, pytorch neural net, and a integer representing the number of levels down the decision tree to search, and makes the "best" move.  You'll likely want to alter the specifics based on your implementation.

NeuralNet4 is my most recent implementation of a neural net object

InputVector takes the Game state and translates it into a vector, so that it can be neural netted

helper contains a function that will play a bunch of games given a NN and record outcomes for reinforcement learning

# My rudimentary solvers

My solvers for the simplified Splendor are in the "Scott Simple Genetic Algorithm" and "Scott Simple Reinforcement Gradient Descent".  The genetic algorithm is good enough to solve the simplest case, but not enough to solve the second simplest.  So far the best I have is the "MultiReinforcement" algorithm, which can very quickly solve the simplest case, but still averages at best ~2.6 moves in the second simplest case (optimal solution is 2 moves).